### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by juanludlf** [aheissenberger/serverless-appsync-offline#1]
Hi, I'm trying to install this package on windows 10. I have tried `npm install` with powershell and git bash but I'm getting the following error:
```
> download --extract -o emulator https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip && ./install.sh

 "." is not recognized as an internal or external command, 
operable program or batch file.
```
Thanks!

**Comment by aheissenberger** [comment]
@juanlu91 I have never used it under windows - you will have to issue this in this repository as this serverless plugin is only an wrapper for this emulator:
https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless
