### ISSUE TITLE
Mapping templates interpetration and Lambda execution

### ISSUE THREAD

**Issue by timgivois** [aheissenberger/serverless-appsync-offline#10]
I'm having two issues. I have created a hello world graphql application. When deploying to remote appsync, I can see it's working correctly. But with `sls-appsync-offline` it seems that it's not interpreting well.

request mapping template:
```
{
    "version": "2017-02-28",
    "operation": "Invoke",
    "payload": {
        "type": "Query",
        "resolver": "helloWorld",
        "arguments":  $utils.toJson($context.arguments)
    }
}

```

Error:
```
{
  "errors": [
    {
      "message": "Cannot find function config for function : undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "helloWorld"
      ]
    }
  ],
  "data": null
}
```

I tried to change the mapping template, and it seems it cannot parse it:
```
{
    "version": "2017-02-28",
    "operation": "Invoke",
    "payload": {
        "type": "Query",
        "resolver": "helloWorld",
        "arguments":  $utils.toJson($context.arguments),
        "handle" : $utils.toJson($context.identity.username)
    }
}

``` 
Error:
```
{
  "errors": [
    {
      "message": "JSON5: invalid character '$' at 8:20",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "helloWorld"
      ]
    }
  ],
  "data": null
}
```

**Comment by aheissenberger** [comment]
@timgivois have been able to solve this problem with the newer version of this package including the latest version of AppSync Emulator ?
I would suggest to submit this problem at the [AppSync Emulator](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless) as this is not a problem of this package.

**Comment by timgivois** [comment]
thanks @aheissenberger, I'll dig deeper to see what's the root cause of this issue and reopen if necessary.

**Comment by aheissenberger** [comment]
@timgivois 

my tests showed that simple substitution is working but the $util functions are not executed and stay in the result which leads to a non valid JSON. Just try to warp all values with quotes

**Comment by timgivois** [comment]
oh, let me check that then, thanks!

**Comment by bboure** [comment]
@aheissenberger @timgivois did you solve that issue?
I am also getting this error: `JSON5: invalid character '$' at 1:1`
It seems indeed that the VTL functions are not interpreted and remain in the output.

**Comment by timgivois** [comment]
yes, the problem is with VTL functions interpretation, I believe that wrapping them with `"` will make the test pass.

**Comment by bboure** [comment]
@timgivois for me, the issue occurs in a response template. 
My template just contains `$util.toJson($context.result.items[0])`
Wrapping with `"` just makes it a string and `$util.toJson($context.result.items[0])` is returned as a string. Value is not interpreted. 

I am still investigating the issue. It has to do with the [emulator](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless) I think and not this serverless plugin.
But since the error you had seems similar, I was wondering if someone had a solution.

Thanks anyway

**Comment by honasassa** [comment]
I got the same error.

This problem occured when using Query, and there is no results.

req.vtl

```
{
    "version" : "2018-05-29",
    "operation" : "Query",
    "query" : {
        "expression": "handle = :handle",
        "expressionValues" : {
            ":handle" : {
                "S" : "${context.identity.username}"
            }
        }
    }
}
```

res.vtl
```
$util.toJson($context.result.items[0])
```

And in appsync online it returns error like this.

```
GraphQL error: Error invoking method 'get(java.lang.Integer)' in java.util.ArrayList at velocity[line 1, column 35]
```

by changing res.vtl, this problem is solved.

```
#if($context.result.items.isEmpty())
    $util.error("Item not found")
#else
    $util.toJson($context.result.items[0])
#end
```

 But why Graphql Error message differs?

**Comment by aheissenberger** [comment]
@kkkkkt  maybe you can ask this question in the repository of the emulator:
https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless
