### ISSUE TITLE
Installing error on windows

### ISSUE THREAD

**Issue by dafne25190** [aheissenberger/serverless-appsync-offline#13]
When I try to install the package I receive this error:

npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 prepare C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74
npm ERR! prepareGitDep > npm run clean && npm run lint && npm run build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 clean C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74
npm ERR! prepareGitDep > rimraf lib dist es coverage
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 lint C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74
npm ERR! prepareGitDep > eslint src demo
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74\src\index.js
npm ERR! prepareGitDep    1:65  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:66  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:60  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:91  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:47  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:54  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   14:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   15:78  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   16:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   17:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   18:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   19:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   20:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   21:58  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   22:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   23:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   24:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   25:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   26:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   27:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   28:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   29:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   30:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   31:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   32:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   33:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   34:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   35:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   36:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   37:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   38:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   39:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   40:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   41:51  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   42:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   43:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   44:2   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   45:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   46:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74\demo\index.js
npm ERR! prepareGitDep    1:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:98  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-5de1ad74\demo\schema.js
npm ERR! prepareGitDep    1:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   14:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   15:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   16:44  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   17:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   18:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   19:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   20:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   21:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   22:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   23:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   24:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   25:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   26:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   27:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   28:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   29:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   30:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   31:44  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   32:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   33:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   34:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   35:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   36:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   37:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   38:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   39:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   40:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   41:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   42:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   43:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep ✖ 102 problems (102 errors, 0 warnings)
npm ERR! prepareGitDep   102 errors, 0 warnings potentially fixable with the `--fix` option.
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! graphql-phone-type@0.0.2 lint: `eslint src demo`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the graphql-phone-type@0.0.2 lint script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T19_22_13_278Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! graphql-phone-type@0.0.2 prepare: `npm run clean && npm run lint && npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the graphql-phone-type@0.0.2 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T19_22_13_360Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T19_22_14_072Z-debug.log
PS C:\Data\work\NinjaCuba\Code\ninjacuba_api> npm install serverless-appsync-offline
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/pianomansam/graphql-phone-type.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/pianomansam/graphql-phone-type.git/': Unknown SSL protocol error in connection to github.com:443
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T20_11_37_498Z-debug.log
PS C:\Data\work\NinjaCuba\Code\ninjacuba_api> npm install serverless-appsync-offline
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 prepare C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae
npm ERR! prepareGitDep > npm run clean && npm run lint && npm run build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 clean C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae
npm ERR! prepareGitDep > rimraf lib dist es coverage
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > graphql-phone-type@0.0.2 lint C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae
npm ERR! prepareGitDep > eslint src demo
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae\src\index.js
npm ERR! prepareGitDep    1:65  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:66  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:60  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:91  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:47  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:54  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   14:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   15:78  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   16:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   17:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   18:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   19:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   20:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   21:58  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   22:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   23:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   24:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   25:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   26:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   27:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   28:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   29:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   30:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   31:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   32:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   33:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   34:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   35:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   36:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   37:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   38:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   39:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   40:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   41:51  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   42:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   43:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   44:2   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   45:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   46:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae\demo\index.js
npm ERR! prepareGitDep    1:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:98  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep C:\Users\Dell\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-fd0700ae\demo\schema.js
npm ERR! prepareGitDep    1:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    2:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    3:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    4:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    5:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    6:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    7:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    8:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep    9:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   10:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   11:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   12:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   13:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   14:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   15:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   16:44  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   17:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   18:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   19:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   20:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   21:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   22:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   23:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   24:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   25:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   26:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   27:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   28:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   29:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   30:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   31:44  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   32:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   33:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   34:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   35:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   36:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   37:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   38:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   39:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   40:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   41:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   42:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep   43:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
npm ERR! prepareGitDep
npm ERR! prepareGitDep ✖ 102 problems (102 errors, 0 warnings)
npm ERR! prepareGitDep   102 errors, 0 warnings potentially fixable with the `--fix` option.
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! graphql-phone-type@0.0.2 lint: `eslint src demo`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the graphql-phone-type@0.0.2 lint script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T20_12_47_408Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! graphql-phone-type@0.0.2 prepare: `npm run clean && npm run lint && npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the graphql-phone-type@0.0.2 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-01-22T20_12_47_510Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

**Comment by lucasvieirasilva** [comment]
same problem!

**Comment by aheissenberger** [comment]
as mentioned by @cbaron this is a problem with the serverless-appsync-plugin:
https://github.com/ConduitVC/aws-utils/issues/73
