### ISSUE TITLE
appsync-emulator-serverless outdated

### ISSUE THREAD

**Issue by theoribeiro** [aheissenberger/serverless-appsync-offline#18]
A few important bug corrections happened in appsync-emulator-serverless and this package is using a reasonably outdated version of it. 

I have been using appsync-emulator-serverless v0.10.0 successfully. Would you consider updating the dependency version requirement? 
I can submit the PR if you prefer. 

Thanks

**Comment by aheissenberger** [comment]
Done - Thanks for the reminder :-)
