### ISSUE TITLE
Create new table  for DynamoDB Local

### ISSUE THREAD

**Issue by davidclochard** [aheissenberger/serverless-appsync-offline#24]
Hey guys,

i'm using your plugin and use the DynamoDB local installation feature. It works wonderfully, but now, i'm wondering how can I create a new table in this local DDB, and add some data.

Could you help me ?

Thanks

**Comment by aheissenberger** [comment]
Hi @davidclochard have a look at the configuration for the AppSync Plugin:
https://github.com/sid88in/serverless-appsync-plugin#configuring-the-plugin

the other option would be to  use an other DynamoDB simulator and only add the connection infos

**Comment by davidclochard** [comment]
@aheissenberger Thanks :D
