### ISSUE TITLE
AppSync without GraphQL

### ISSUE THREAD

**Issue by mhrisse** [aheissenberger/serverless-appsync-offline#29]
Hi everyone!

We are looking to use AppSync with Lambda and without DynamoDB, we probably use DocumentDB/Mongo or Aurora. What is the best way to disable DynamoDB and not having it installed at all locally, while keeping `serverless-appsync-plugin` and `serverless-appsync-offline` working?

Cheers
M

**Comment by aheissenberger** [comment]
This will expect an external DynamoDB  and does not start the internal one:
custom:
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "http://localhost:8000"

This should work for your requirements.

**Comment by mhrisse** [comment]
Thanks, seems to work so far. Will get back here when we got the other issue resolved.
