### ISSUE TITLE
Read schema file from serverless-appsync-plugin config

### ISSUE THREAD

**Issue by kvnwolf** [aheissenberger/serverless-appsync-offline#3]
On my configuration for the `serverless-appsync-plugin` I have configured the schema to be read from `graphql/schema.graphql` but this plugin is not using that configuration, so I get the error `ERROR: Error: schema file: /Users/kevinwolf/dev/gopato-cloud-services/schema.graphql must exist`

**Comment by aheissenberger** [comment]
This is only a wrapper - the functionality for the  interpretation of the configuration is provided by this library. Please ask your issue [there](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless).

**Comment by davidclochard** [comment]
Hi @kevinwolfcr , did you solved your problem ? I got the same here

**Comment by johnlimed** [comment]
For anyone else that encountered this, and want to config a custom path to your schema, you can add this into your serverless.yml config:

```
custom
    appsync-offline:
      schema: path/to/schema.graphql
```

If you have multiple schemas defined in your appSync config, I've read that others got a workaround to concat the schemas into one and either put it in the default location or define your config to point to that custom location.
