### ISSUE TITLE
Conflicting peer dependencies

### ISSUE THREAD

**Issue by vicary** [aheissenberger/serverless-appsync-offline#31]
The current version of `serverless-appsync-offline` has indirect dependencies that conflicts in their peer dependencies of `graphql`. `npm install` output extracted below,

```
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-link-http@1.3.1 requires a peer of graphql@^0.11.0 but none is installed. You must install peer dependencies yourself
```

I suggest updating `graphql-*` packages to at least those versions that depends on `graphql@14.x` for long term stability.

**Comment by aheissenberger** [comment]
This are peer dependencies which are under control of a sub package  - please contact the maintainers here:
https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless
