### ISSUE TITLE
Schema Stitching

### ISSUE THREAD

**Issue by leonfb** [aheissenberger/serverless-appsync-offline#32]
Hello,

My serverless file uses schema stitching for clarity. But it seems is not supported:

`Serverless: ERROR: Error: schema file: /<path>/schema.graphql must exist
`

Is there a workaround or going to be supported at any point?
Thank you

**Comment by aheissenberger** [comment]
Are you sure this is supported by AWS AppSync? This is only a wrapper - you will need to ask hier if this is supported:
https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless
