### ISSUE TITLE
cannot invoke lambda functions in offline

### ISSUE THREAD

**Issue by ghost** [aheissenberger/serverless-appsync-offline#37]

**Comment by aheissenberger** [comment]
this is only the plugin to embed [AppSync Emulator](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless) and depends on [Serverless-AppSync-Plugin](https://github.com/sid88in/serverless-appsync-plugin).

To help you I need at least a example code which proves you problem - please keep in mind that specific questions related to configuration or emulation are better asked here:
* [AppSync Emulator](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless) 
* [Serverless-AppSync-Plugin](https://github.com/sid88in/serverless-appsync-plugin)

**Comment by praisegeek** [comment]
@aheissenberger, I am currently battling with this issue. I started a thread on AppSync Emulator Serverless.

[Issue](https://github.com/ConduitVC/aws-utils/issues/152)

**Comment by praisegeek** [comment]
This has been fixed in AppSync Emulator in the latest version. ^0.14.3
