### ISSUE TITLE
Incorrect string equality in templates

### ISSUE THREAD

**Issue by cyberwombat** [aheissenberger/serverless-appsync-offline#38]
I am wanting to compare strings and am unable to. Consider this example:
```
#set($foo = "a")
#set($bar = "a")

#if($foo == $bar) // Not the same
#if($foo == $bar.toString()) // The same
#if($foo.toString() == $bar) // The same
```
If I cast a single one then it matches?

I tried using the current version of velocityjs which appears to be the rendering engine and it works fine. Also someone tried it live on AWS and it works - just not when running locally.

My setup:
```
"serverless": "^1.47.0",
"serverless-appsync-offline": "^1.3.3",
"serverless-appsync-plugin": "^1.1.2",
"serverless-dynamodb-local": "^0.2.38",
```

My template:
```
#set($foo="a")
#set($bar="a")
#if($foo==$bar)
  same
#else
 not same
#end
```
I am loading this using `SLS_DEBUG=* NODE_DEBUG=appsync-* yarn sls appsync-offline start` and testing with graphiQL

**Comment by aheissenberger** [comment]
Hi @cyberwombat  - this lib is a wrapper for [appsync-emulator-serverless](https://github.com/ConduitVC/aws-utils) maybe not all features are supported - please rise an issue there to get a proper answer.
