### ISSUE TITLE
Lambda Resolvers

### ISSUE THREAD

**Issue by builtbyproxy** [aheissenberger/serverless-appsync-offline#4]
Hello, The README.md for serverless-appsync-plugin references this package [here]
It mentions support for Lambda Resolvers as well. 

Therefore I was wondering; 

- [ ] Does this plugin support Lambda Resolvers? 
- [ ] If so would it be possible to update the README.md with a code example of plugging in a lambda resolver without the dynamodb.

My Specific use case for this is dealing with my current project's stack that goes
appsync -> serverless/Lambda -> Postgraphile -> PostgresQL 

Thankyou

 [here]: <https://github.com/sid88in/serverless-appsync-plugin#offline-support>

**Comment by aheissenberger** [comment]
I have only wrapped this library "[appsync-emulator-serverless](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless)" and have no experience with the lambda resolvers - but anything wich does work with the library works with this plugin.

Please ask there if they can provide you with a sample code.

**Comment by builtbyproxy** [comment]
Fantastic thanks for getting back to me @aheissenberger

**Comment by aheissenberger** [comment]
> Fantastic thanks for getting back to me @aheissenberger

sorry - I messed up - you need to go to  "[appsync-emulator-serverless](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless)" to get the answer but I am sure that lamdas are supported

**Comment by builtbyproxy** [comment]
Love it. Ive just deployed to AWS Appsync for now however this needs to be setup correctly when more devs join for local development. Ill get back to you with code examples and a PR even for lambdas if I can get it to work. 

Whilst I have you though, to implement this in the yaml does it go like: 

```
custom: 
	appsync-offline:
	    port: 62222
	    dynamodb:
	      server:
	        port: 8000
	accountId: 496816422666 
	appSync:
	    name:  myAPI
	    apiId: abc123
	    authenticationType: AMAZON_COGNITO_USER_POOLS
	    userPoolConfig:
	    awsRegion: us-east-1
	      defaultAction: ALLOW
	      userPoolId: us-east-1-randomSlug
```

.... and so on? 

Or should I wrap the appSync config a different way? 

Thanks

**Comment by builtbyproxy** [comment]
**Update** for anyone, see this [boilerplate](https://github.com/builtbyproxy/appsync-serverless-boilerplate) and specifically it's serverless.yml file in the server folder
