### ISSUE TITLE
Publish 1.4.0

### ISSUE THREAD

**Issue by LMulvey** [aheissenberger/serverless-appsync-offline#42]
Hi there,

In a026ad5cbead9a2147d05bf0a89bafc6754bc7b1, you updated the semver for the `appsync-emulator-serverless` package to `^0.14.0` which is extremely valuable as this version contains a fix for flattening dataSource and mappingTemplate entries in the `serverless` configuration.

You had an additional commit to bump this package's version to `1.4.0` (714ca0273e6b1c155b2314e4420e847085210ebd) however, this was never actually published to npm (latest version published is still `1.3.3`. This update would cut a ton of bloat from our current Serverless config. We're currently running on our own fork of this package to satisfy this dep requirement but it would be great if it could be published so we could stay in sync and not maintain a separate fork. 

Thanks!

**Comment by barendb** [comment]
👍

**Comment by aheissenberger** [comment]
updated to latest version
