### ISSUE TITLE
Unable to install this package with Node16.3.1

### ISSUE THREAD

**Issue by himharsh1997** [aheissenberger/serverless-appsync-offline#52]
`This issue is happened when I switch from nodejs 12.21.0 -> 16.13.1.   Below image is last thing which I saw on install of this package after which terminal also get hanged.`
<img width="759" alt="Screenshot 2022-01-04 at 8 05 14 PM" src="https://user-images.githubusercontent.com/25052801/148074918-c541e9d5-fc54-449c-ab29-71bd969a992b.png">
0

**Comment by himharsh1997** [comment]
@aheissenberger Pls help us.

**Comment by himharsh1997** [comment]
@aheissenberger @mattgibson  Pls help me as other package like serverless-appsync-plugin, serverless-offline are getting installed successfully but not this.

**Comment by himharsh1997** [comment]
@aheissenberger @mattgibson @Mystogab ??

**Comment by and3rson** [comment]
Same here. Is this plugin still alive?

**Comment by aheissenberger** [comment]
@himharsh1997 
The problem is related to this:
https://github.com/moscajs/mosca/issues/799

**Comment by aheissenberger** [comment]
@himharsh1997 this problem with looping only exists when installing with `npm` - installing with `yarn` works without a problem. As the problem exists in the `@conduitvc/mosca` sub package of a dependency `@conduitvc/appsync-emulator-serverless` which does not provide a newer version I cannot fix this. Please ask the maintainer of the packages for help.

**Comment by Luis-Enrique93** [comment]
mosca it's archived, it was moved to Aedes, so this issue won't be solved
